#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
- name: ssh_config/gen-keys | Create ssh keys
  ansible.builtin.shell: |
    ! test -f {{ item }} &&
    mkdir -p $(dirname {{ item }}) &&
    ssh-keygen -f {{ item }} -q -N "" -C {{ ansible_host }}
  args:
    executable: /bin/bash
    creates: "{{ item }}"
  loop: "{{
      ssh_config__services |
      json_query('[*].hosts[*].key') |
      flatten
    }}"
  tags:
    - install
