#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
#- name: Configure | Create ssh keys
  #shell: |
    #! test -f {{ item }} &&
    #mkdir -p $(dirname {{ item }}) &&
    #ssh-keygen -b 4096 -f {{ item }} -q -N ""
  #args:
    #executable: /bin/bash
    #creates: "{{ item }}"
    #warn: false
  #with_items: "{{
    #ssh_config__services |
    #json_query('[*].hosts[*].key') |
    #flatten
  #}}"
  #tags:
    #- install

