#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
#######################  install  ######################################
  # @TODO:  <07-04-19, Evgeniy Blinov <evgeniy_blinov@mail.ru>> # refactor settings

- name: ssh_config/config | Create config settings
  ansible.builtin.copy:
    content: |-
      # vim: set noet ci pi sts=0 sw=4 ts=4 :
    dest: >-
      {{ ssh_config__dir_path }}/00_settings
    mode: 0600
    force: false
  loop: "{{ ssh_config__services }}"
  tags:
    - install

- name: ssh_config/config | Add config settings
  blockinfile:
    path: >-
      {{ ssh_config__dir_path }}/00_settings
    block: |
      {% for option, value in ssh_config__settings.items() %}
      {{ option}} {{ value }}
      {% endfor %}
    mode: 0600
    state: present
    insertafter: '#\s*vim\s*'
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ssh_config"
  tags:
    - install

- name: ssh_config/config | Create config
  ansible.builtin.copy:
    content: |-
      # vim: set noet ci pi sts=0 sw=4 ts=4 :
    dest: >-
      {{ ssh_config__dir_path }}/{{ "%02d" | format(item.priority | default(ssh_config__priority, True)) }}_{{ ssh_config__prefix }}{{ item.name }}
    mode: 0600
    force: false
  loop: "{{ ssh_config__services }}"
  tags:
    - install

- name: ssh_config/config | Add hosts
  blockinfile:
    path: >-
      {{ ssh_config__dir_path }}/{{ "%02d" | format(item.priority | default(ssh_config__priority, True)) }}_{{ ssh_config__prefix }}{{ item.name }}
    block: "{{ lookup('template', 'ssh_config') }}"
    mode: 0600
    state: present
    insertafter: '#\s*vim\s*'
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ssh_config"
  loop: "{{ ssh_config__services }}"
  tags:
    - install

- name: Configure | Make ssh config
  shell: |
    cp {{ ssh_config__config_path }} {{ ssh_config__config_path }}-$(date +%s).bak 2> /dev/null ; \
    cat {{ ssh_config__dir_path }}/* > {{ ssh_config__config_path }}
  tags:
    - install
#######################  install  ######################################

#######################  uninstall  ####################################

- name: Configure | Uninstall ssh config
  file:
    dest: "{{ ssh_config__item_name_prefix }}{{ item.name }}"
    state: absent
  with_items: "{{ ssh_config__rm_services }}"
  tags:
    - uninstall
#######################  uninstall  ####################################
