#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
#######################  install  ######################################
  # @TODO:  <07-04-19, Evgeniy Blinov <evgeniy_blinov@mail.ru>> # refactor settings
- name: Configure | ssh_config settings
  shell:
    cmd: |
      # Create settings if not found some settings
      grep '^(Server|TCPKeepAlive|Control).*' -qP  {{ ssh_config__dir_path }}/* || \
      cat > {{ ssh_config__dir_path }}/00_settings <<- 'EOF'
      # vim: set noet ci pi sts=0 sw=4 ts=4 :
      TCPKeepAlive={{ ssh_config__settings.TCPKeepAlive }}
      {% if ssh_config__settings.ServerAliveInterval is defined %}
      ServerAliveInterval={{ ssh_config__settings.ServerAliveInterval }}
      {% endif %}
      {% if ssh_config__settings.ServerAliveCountMax is defined %}
      ServerAliveCountMax={{ ssh_config__settings.ServerAliveCountMax }}
      {% endif %}
      Compression={{ ssh_config__settings.Compression }}
      ControlMaster {{ ssh_config__settings.ControlMaster }}
      ControlPath {{ ssh_config__settings.ControlPath }}
      ControlPersist {{ ssh_config__settings.ControlPersist }}
      EOF
  args:
    executable: /bin/bash

- name: ssh_config/config | Create config
  ansible.builtin.copy:
    content: |-
      # vim: set noet ci pi sts=0 sw=4 ts=4 :
    dest: >-
      {{ ssh_config__dir_path }}/{{ item.priority | default(ssh_config__priority, True) }}-{{ ssh_config__prefix }}{{ item.name }}
    mode: 0600
    force: false
  loop: "{{ ssh_config__services }}"
  tags:
    - install

- name: ssh_config/config | Add hosts
  blockinfile:
    path: >-
      {{ ssh_config__dir_path }}/{{ item.priority | default(ssh_config__priority, True) }}-{{ ssh_config__prefix }}{{ item.name }}
    block: "{{ lookup('template', 'ssh_config') }}"
    mode: 0600
    state: present
    insertafter: '#\s*vim\s*'
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ssh_config"
  loop: "{{ ssh_config__services }}"
  tags:
    - install

- name: Configure | Make ssh config
  shell: |
    cp {{ ssh_config__config_path }} {{ ssh_config__config_path }}-$(date +%s).bak 2> /dev/null ; \
    cat {{ ssh_config__dir_path }}/* > {{ ssh_config__config_path }}
  tags:
    - install
#######################  install  ######################################

#######################  uninstall  ####################################

- name: Configure | Uninstall ssh config
  file:
    dest: "{{ ssh_config__item_name_prefix }}{{ item.name }}"
    state: absent
  with_items: "{{ ssh_config__rm_services }}"
  tags:
    - uninstall
#######################  uninstall  ####################################
